/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

#include <tcMenu.h>
#include "tcMenuOBD_menu.h"

// Global variable declarations

U8g2GfxMenuConfig gfxConfig;
U8g2MenuRenderer renderer;

// Global Menu Item declarations

const AnalogMenuInfo minfoGAUGE4PID = { "GAUGE 4 PID", 8, 0xffff, 134, NO_CALLBACK, 0, 1, "" };
AnalogMenuItem menuGAUGE4PID(&minfoGAUGE4PID, 0, NULL);
const AnalogMenuInfo minfoGAUGE3PID = { "GAUGE 3 PID", 7, 11, 134, NO_CALLBACK, 0, 1, "" };
AnalogMenuItem menuGAUGE3PID(&minfoGAUGE3PID, 0, &menuGAUGE4PID);
const AnalogMenuInfo minfoGAUGE2PID = { "GAUGE 2 PID", 2, 7, 134, NO_CALLBACK, 0, 1, "" };
AnalogMenuItem menuGAUGE2PID(&minfoGAUGE2PID, 0, &menuGAUGE3PID);
const AnalogMenuInfo minfoGAUGE1PID = { "GAUGE 1 PID", 1, 9, 134, NO_CALLBACK, 0, 1, "" };
AnalogMenuItem menuGAUGE1PID(&minfoGAUGE1PID, 0, &menuGAUGE2PID);
ListRuntimeMenuItem menuNewSubMenuSupportedPIDLIST(10, 0, fnNewSubMenuSupportedPIDLISTRtCall, NULL);
RENDERING_CALLBACK_NAME_INVOKE(fnNewSubMenuRtCall, backSubItemRenderFn, "New SubMenu", -1, NULL)
const SubMenuInfo minfoNewSubMenu = { "New SubMenu", 9, 0xffff, 0, NO_CALLBACK };
BackMenuItem menuBackNewSubMenu(fnNewSubMenuRtCall, &menuNewSubMenuSupportedPIDLIST);
SubMenuItem menuNewSubMenu(&minfoNewSubMenu, &menuBackNewSubMenu, &menuGAUGE1PID);
const ConnectorLocalInfo applicationInfo = { "tcMenuOBD", "1d88392a-c2dd-4b5d-99a6-7b8d1ae591b5" };

// Set up code

void setupMenu() {
    prepareBasicU8x8Config(gfxConfig);
    renderer.setGraphicsDevice(&gfx, &gfxConfig);
    switches.initialise(ioUsingArduino(), true);
    menuMgr.initForUpDownOk(&renderer, &menuNewSubMenu, 12, 14, 13);
}

