/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

#ifndef MENU_GENERATED_CODE_H
#define MENU_GENERATED_CODE_H

#include <tcMenu.h>

#include "tcMenuU8g2.h"
#include <RuntimeMenuItem.h>

// all define statements needed
#define DISPLAY_VARIABLE gfx
#define DISPLAY_TYPE U8G2_SSD1306_128X64_NONAME_F_SW_I2C
#define DISPLAY_CONFIG 
#define PULLUP_LOGIC true
#define INTERRUPT_SWITCHES false
#define SWITCH_IODEVICE 
#define ENCODER_UP_PIN 12
#define ENCODER_DOWN_PIN 14
#define ENCODER_OK_PIN 13

// all variables that need exporting
extern U8G2_SSD1306_128X64_NONAME_F_SW_I2C gfx;
extern U8g2GfxMenuConfig gfxConfig;
extern U8g2MenuRenderer renderer;

// all menu item forward references.
extern AnalogMenuItem menuGAUGE4PID;
extern AnalogMenuItem menuGAUGE3PID;
extern AnalogMenuItem menuGAUGE2PID;
extern AnalogMenuItem menuGAUGE1PID;
extern ListRuntimeMenuItem menuNewSubMenuSupportedPIDLIST;
extern BackMenuItem menuBackNewSubMenu;
extern SubMenuItem menuNewSubMenu;
extern const ConnectorLocalInfo applicationInfo;

// Callback functions must always include CALLBACK_FUNCTION after the return type
#define CALLBACK_FUNCTION

int fnNewSubMenuSupportedPIDLISTRtCall(RuntimeMenuItem* item, uint8_t row, RenderFnMode mode, char* buffer, int bufferSize);

void setupMenu();

#endif // MENU_GENERATED_CODE_H
